---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/lan/
    - /bin/rm $DEPLOYPATH/* -Rf
    - /bin/cp -R * $DEPLOYPATH
    - source $HOME/nodevenv/lan/24/bin/activate && cd $DEPLOYPATH
    - npm install